# Numpy

## SingleDimensional Array

In [10]:
# !pip install numpy

In [11]:
import numpy as np

In [12]:
arr1 = np.array([1,2,3])
print("arr type : ", type(arr1))
arr1

arr type :  <class 'numpy.ndarray'>


array([1, 2, 3])

In [13]:
arr1.shape

(3,)

In [14]:
# np.arange(10)
np.arange(5,101,5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [15]:
np_arr1 = arr1 + 2 # add 2 to all elements of arr1
np_arr1

array([3, 4, 5])

In [16]:
np_arr_add=np.add( arr1, np_arr1) # add elements of arr1 to all elements of np_arr1
np_arr_add

array([4, 6, 8])

In [17]:
np_arr_subtract=np.subtract(np_arr_add,np_arr1)  # subtract elements of arr1 to all elements of np_arr1
np_arr_subtract

array([1, 2, 3])

In [18]:
%timeit [i**4 for i in range(10000)]

1.05 ms ± 147 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [19]:
%timeit np.arange(10000)**4

45 μs ± 4.68 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [20]:
np.zeros_like(np_arr1)

array([0, 0, 0])

In [21]:
np.ones_like(np_arr1)

array([1, 1, 1])

## MultiDimensional Array

In [22]:
np_2D_arr1 = np.array([[1,2,3],[4,5,6]])
np_2D_arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np_2D_arr1[1,2]

np.int64(6)

In [24]:
np_2D_arr1[(np_2D_arr1<6) & (np_2D_arr1>2)] = 4
np_2D_arr1

array([[1, 2, 4],
       [4, 4, 6]])

In [25]:
np.zeros((4,4),dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [26]:
np.full((4,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.diag([3,5,6,7])

array([[3, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

## Coppy np array

In [29]:
np_arr_A = np.arange(1,11)
np_arr_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np_arr_B = np_arr_A
np_arr_B

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np_arr_B[2] = 7
np_arr_B

array([ 1,  2,  7,  4,  5,  6,  7,  8,  9, 10])

In [32]:
np_arr_A

array([ 1,  2,  7,  4,  5,  6,  7,  8,  9, 10])

In [33]:
np.shares_memory(np_arr_A,np_arr_B)

True

In [34]:
np_arr_C = np_arr_A.copy()
np_arr_C

array([ 1,  2,  7,  4,  5,  6,  7,  8,  9, 10])

In [35]:
np_arr_C[2] = 3
np_arr_C

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
np_arr_A

array([ 1,  2,  7,  4,  5,  6,  7,  8,  9, 10])

In [37]:
np.shares_memory(np_arr_A,np_arr_C)

False

## np random functions

In [38]:
np_rd1= np.random.random()
np_rd1

0.7416163811510004

In [39]:
np_rd2 = np.random.random((3,2))
np_rd2

array([[0.3953375 , 0.7053039 ],
       [0.68954943, 0.07034353],
       [0.29056272, 0.48326162]])

In [40]:
np_rdr2 =np.round(np_rd2,2)
np_rdr2

array([[0.4 , 0.71],
       [0.69, 0.07],
       [0.29, 0.48]])

In [41]:
np.random.seed(1)
np_rd3= np.random.random()
np_rd3

0.417022004702574

In [42]:
np_rd4 = np.random.randint(low=100,high=200,size=(4,5))
np_rd4

array([[112, 172, 109, 175, 105],
       [179, 164, 116, 101, 176],
       [171, 106, 125, 150, 120],
       [118, 184, 111, 128, 129]], dtype=int32)

In [43]:
np_rd4.shape

(4, 5)

In [44]:
np_rd4.reshape(2,10)

array([[112, 172, 109, 175, 105, 179, 164, 116, 101, 176],
       [171, 106, 125, 150, 120, 118, 184, 111, 128, 129]], dtype=int32)

In [45]:
np.sin(np.array([1,2,3,4,5]))

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [46]:
np.exp(np.array([1,2,3,4,5]))

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [47]:
np.sum(np.array([1,2,3,4,5]))

np.int64(15)