In [142]:
import numpy as np

In [143]:
np.array([12.23, 13.32, 100, 36.32])

array([ 12.23,  13.32, 100.  ,  36.32])

In [144]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [145]:
zero = np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [146]:
zero[6] = 11
zero

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [147]:
array = np.array(range(12,38))
print(array)
rearray = array[::-1]
print(rearray)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [148]:
np_2d_array = np.ones((5,5))
np_2d_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [149]:
np_2d_array[1:-1, 1:-1] = 0
np_2d_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [150]:
np_2d_array = np.ones((3,3))
np_2d_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [151]:
np.pad(np_2d_array,1,'constant')

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [152]:
np_2d_array = np.zeros((8,8))
np_2d_array

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [153]:
np_2d_array[::2, 1::2] = 1
np_2d_array[1::2, ::2] = 1
np_2d_array
np_2d_array = np.indices((8,8)).sum(axis=0)%2
np_2d_array

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [154]:
lst = [1,2,3,4,5,6,7,8]
tpl = ((8, 4, 6),(1, 2, 3))
print(np.array(lst))
print(np.array(tpl))

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


In [155]:
np_arr = np.array([10, 20, 30])
print(np_arr)
print(np.append(np_arr, [40, 50, 60, 70, 80, 90]))

[10 20 30]
[10 20 30 40 50 60 70 80 90]


In [156]:
np_vec_arr = np.array([1.00000000+0.j, 0.70710678+0.70710678j])
print(np_vec_arr.real)
print(np_vec_arr.imag)

[1.    0.707]
[0.    0.707]


In [157]:
print("Size of the array: ",np_arr.size)
print("Length of one array element in bytes: ",np_arr.itemsize)
print("Total bytes consumed by the elements of the array: ",np_arr.size * np_arr.itemsize)

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


In [158]:
Array1 = np.array([0, 10, 20, 40, 60])
Array2= np.array([10, 30, 40]) 
print(np.intersect1d(Array1, Array2))

[10 40]


In [159]:
Array1 = np.array([0, 10, 20, 40, 60, 80])
Array2= np.array([10, 30, 40, 50, 70, 90])
print(np.setdiff1d(Array1, Array2))

[ 0 20 60 80]


In [160]:
Array1 = np.array([0, 10, 20, 40, 60, 80])
Array2= np.array([10, 30, 40, 50, 70])
print(np.setxor1d(Array1, Array2))

[ 0 20 30 50 60 70 80]


In [161]:
a = np.array([1, 2])
b = np.array([4, 5])
print("a > b")
print(a > b)
print("a >= b")
print(a >= b)
print("a < b")
print(a < b)
print("a <= b")
print(a <= b)

a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


In [162]:
np_arr = np.array([[10, 20, 30],[20, 40, 50]])
print(np_arr.ravel())

[10 20 30 20 40 50]


In [163]:
np_arr = np.array([[2, 4, 6],[6, 8, 10]],dtype=np.int32)
np_arr = np_arr.astype(np.float64)
np_arr

array([[ 2.,  4.,  6.],
       [ 6.,  8., 10.]])

In [164]:
np_arr = np.eye(3)
np_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [165]:
np_arr = np.tri(4, 3, -1)
np_arr

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [166]:
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])
np_arr = np.concatenate((a, b), axis=1)
print(np_arr)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [167]:
np_arr = np.zeros(10)
np_arr.flags.writeable = False
print("Test the array is read-only or not:")
try:
    np_arr[0] = 1
except ValueError as e:
    print(f"Traceback (most recent call last):\nValueError: {e}")


Test the array is read-only or not:
Traceback (most recent call last):
ValueError: assignment destination is read-only


In [168]:
np_arr = np.arange(12).reshape(3, 4)
print("Original array elements:\n", np_arr)
print("New array elements:\n", np_arr * 3)

Original array elements:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array elements:
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [169]:
np_arr = np.array([[0, 1], [2, 3], [4, 5]])
py_list = np_arr.tolist()
print(py_list)

[[0, 1], [2, 3], [4, 5]]


In [170]:
np_arr = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478])
np.set_printoptions(precision=3)
print(np_arr)


[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


In [171]:
np_arr = np.array([ 1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
np.set_printoptions(precision=3, suppress=True)
print(np_arr)

[   0.       1.6   1200.       0.235]


In [172]:
np_arr1 = np.array([[10, 20, 30], [40, 50, 60]])
np_arr2 = np.array([[100], [200]])
np_arr = np.append(np_arr1, np_arr2, axis=1)
print(np_arr)

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [173]:
np_arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
result = np.delete(np_arr, [0, 3, 4])
print(result)

[ 20  30  60  70  80  90 100]
